// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV9-g-0hxE_hR_IUyay2vW0zaO3E_egso',
    appId: '1:473513343644:web:64af15a7fe9211fa7d4b59',
    messagingSenderId: '473513343644',
    projectId: 'chatapp-68b83',
    authDomain: 'chatapp-68b83.firebaseapp.com',
    storageBucket: 'chatapp-68b83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBfJAS23HjEngQokKoBlSD09sgwCnZISs',
    appId: '1:473513343644:android:c3f2565d4034a7c67d4b59',
    messagingSenderId: '473513343644',
    projectId: 'chatapp-68b83',
    storageBucket: 'chatapp-68b83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUWWAVq_gBPk9ivnIUOYsgwKy5xqLUVg0',
    appId: '1:473513343644:ios:d8a10ec289c47b6b7d4b59',
    messagingSenderId: '473513343644',
    projectId: 'chatapp-68b83',
    storageBucket: 'chatapp-68b83.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUWWAVq_gBPk9ivnIUOYsgwKy5xqLUVg0',
    appId: '1:473513343644:ios:d8a10ec289c47b6b7d4b59',
    messagingSenderId: '473513343644',
    projectId: 'chatapp-68b83',
    storageBucket: 'chatapp-68b83.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV9-g-0hxE_hR_IUyay2vW0zaO3E_egso',
    appId: '1:473513343644:web:f95ed7d7f315cfe57d4b59',
    messagingSenderId: '473513343644',
    projectId: 'chatapp-68b83',
    authDomain: 'chatapp-68b83.firebaseapp.com',
    storageBucket: 'chatapp-68b83.appspot.com',
  );

}